version: '3.8'
services:
  todoapp:
    image: codecrasher2/todoapp:latest
    ports:
      - "8080:8080"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - AWS_REGION=eu-west-1
      - ASPNETCORE_ENVIRONMENT=Development
    deploy:
      replicas: 3
    networks:
      - todo-network

networks:
  todo-network:
    driver: overlay