name: 'Setup SSH via Bastion'
description: 'Configures SSH access to manager node via bastion host'
inputs:
  deploy-key:
    description: 'SSH private key for authentication'
    required: true
  bastion-host:
    description: 'Bastion host IP or hostname'
    required: true
  manager-private-ip:
    description: 'Manager node private IP'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup SSH configuration
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.deploy-key }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # SSH config for bastion jump host
        cat > ~/.ssh/config << 'EOF'
        Host bastion
          HostName ${{ inputs.bastion-host }}
          User ec2-user
          IdentityFile ~/.ssh/id_rsa
          StrictHostKeyChecking accept-new
          ConnectTimeout 30
          ServerAliveInterval 60
          ServerAliveCountMax 3

        Host manager
          HostName ${{ inputs.manager-private-ip }}
          User ec2-user
          IdentityFile ~/.ssh/id_rsa
          ProxyJump bastion
          StrictHostKeyChecking accept-new
          ConnectTimeout 30
          ServerAliveInterval 60
          ServerAliveCountMax 3
        EOF

    - name: Test SSH connectivity
      shell: bash
      run: |
        echo "Testing bastion connection..."
        ssh bastion "echo 'Bastion connected'"

        echo "Testing manager connection via bastion..."
        ssh manager "docker --version && docker node ls"